[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solanaidle = "2bDsZj9EiF81YYqQbXhxU8rQ6HAqRfTQXJH4BT5qHFtK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keys/dev.json"

[workspace]
members = ["programs/*"]
