[features]
seeds = false
skip-lint = false

[programs.devnet]
vrf_roller = "3khuFQS11YeGuUUhoxLmz6fPi9Dsu6FahXLyGrzpbhUt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keys/dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
