[features]
seeds = false
skip-lint = false

[programs.devnet]
boss_tracker = "GtL43yR1JyZPjcbH8LkCj5j5aDdCTXkWH9K1xTWZa5Zr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keys/dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
